export const PAGE_SIZE = 20; // Pagination size to limit number of requets to the API
export const API_LIMIT = 1500; // Limit of daily requets per WU API key: 1500
export const MINUTES_TO_FETCH_NEW_DATA = 15; // Gets data from DB if user reloads within this time.
export const historyConditionsMock = {
  stationID: "",
  tz: "",
  obsTimeUtc: "",
  obsTimeLocal: "",
  epoch: null,
  lat: null,
  lon: null,
  solarRadiationHigh: null,
  uvHigh: null,
  winddirAvg: null,
  humidityHigh: null,
  humidityLow: null,
  humidityAvg: null,
  metric: {
    dewptAvg: null,
    dewptHigh: null,
    dewptLow: null,
    heatindexAvg: null,
    heatindexHigh: null,
    heatindexLow: null,
    precipRate: null,
    precipTotal: null,
    pressureMax: null,
    pressureMin: null,
    pressureTrend: null,
    tempAvg: null,
    tempHigh: null,
    tempLow: null,
    windchillAvg: null,
    windchillHigh: null,
    windchillLow: null,
    windgustAvg: null,
    windgustHigh: null,
    windgustLow: null,
    windspeedAvg: null,
    windspeedHigh: null,
    windspeedLow: null,
  },
};
